name: CI Feature Branch

on:
  push:
    branches:
      - 'feature/refatoracao'

jobs:
  build:
    name: Build (com cache de dependências)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache do npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Instalar dependências
        run: npm ci

      - name: Build de produção
        run: npm run build

  # test:
  #   name: Testes (com cache de dependências)
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout do código
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Cache do npm
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  #     - name: Instalar dependências
  #       run: npm ci

  #     - name: Rodar testes
  #       run: npm test