name: Pull Request Check

on:
  pull_request:
    branches: [ main ] # Só quando o PR tem como destino a branch "main"

jobs:
  test:
    name: Rodar testes na Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test
